# sypint1-www21.yml
---
- hosts: 127.0.0.1
  connection: local
  tasks:
  - name: Set hostname
    hostname: name=www21-apache.fsclass.localdomain
  - name: Update hosts
    replace: dest=/etc/hostname regexp='localhost.localdomain' replace='www21-apache.fsclass.localdomain'
  - name: Install networkmanager
    yum: name=NetworkManager-glib state=present
  - name: Configure networking
    nmcli: conn_name="eno16777736" type=ethernet ip4=10.10.2.21/24 gw4=10.10.2.2 dns4=8.8.8.8 state=present
  - name: Restart networking
    service: name=network enabled=yes state=restarted
  - name: Install web services
    yum: name={{ item }} state=present
    with_items:
    - httpd
    - php
    - php-mysql
    - php-gd
    - php-mbstring
    - git
    - wget
    - nano
    - curl
  - name: Open firewall for port 80
    firewalld: service=http permanent=true state=enabled
  - name: SELinux Permissive
    selinux: policy=targeted state=permissive
  - name: Git clone WolfCMS
    git: repo=https://github.com/wolfcms/wolfcms.git force=yes dest=/var/www/html/wolfsqlite
  - name: Create SQLite DB directory
    file: path=/var/www/html/db state=directory mode=0777
  - name: Set write on config file
    file: path=/var/www/html/wolfsqlite/config.php mode=0666
  - name: Set write on public
    file: path=/var/www/html/wolfsqlite/public state=directory mode=0777
  - name: rename htaccess
    command: mv /var/www/html/wolfsqlite/_.htaccess /var/www/html/wolfsqlite/.htaccess
  - name: Update htaccess
    lineinfile: dest=/var/www/html/wolfsqlite/.htaccess regexp="^#php_flag magic_quotes_gpc" line="php_flag magic_quotes_gpc off"
  - name: Set rewrite path
    lineinfile: dest=/var/www/html/wolfsqlite/.htaccess regexp="^RewriteBase /wolfcms/" line="RewriteBase /wolfsqlite/"
  - name: Allow overrides in httpd config
    lineinfile: dest=/etc/httpd/conf/httpd.conf regexp="^AllowOverride" insertafter="^<Directory \"/var/www/html\">" line="AllowOverride All"
  - name: Restart httpd
    service: name=httpd enabled=yes state=restarted
  - debug: msg="Server configuration complete. You must run web installer at http://10.10.2.21/wolfsqlite to continue."
  - name: Rebooting machine
    command: shutdown -r now

