# sypint1-www21.yml
---
- hosts: localhost
  tasks:
    - name: Set hostname
      hostname: name=www21-apache.fsclass.localdomain
      replace: dest=/etc/hostname regexp='localhost.localdomain' replace='www21-apache.fsclass.localdomain'
    - name: Configure networking
      nmcli: conn_name="eno16777736" type=ethernet ip4=10.10.2.21/24 gw4=10.10.2.2 dns4=["8.8.8.8"] state=present autoconnect=yes
      service: name=networking enabled=yes state=restarted
    - name: Install web services
      yum: name={{ item }} state=present
      with_items:
        - httpd
        - php
        - php-mysql
        - php-gd
        - php-mbstring
        - git
        - wget
        - nano
        - curl


